name: Publish to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
          HF_SECRET: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Using 'oauth' as the username tells Hugging Face to process the incoming string purely as a token
          git push --force https://oauth:$HF_SECRET@huggingface.co/benjaminy/white_latte main
